swagger: '2.0'
info:
  title: AI Customer Service API
  description: 'AI Customer Service application, built during the Cloud and Big Data course at Columbia University.'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /chatbot:
    post:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in one or more messages from the client and returns
        one or more messages as a response. The API leverages the NLP
        backend functionality, paired with state and profile information
        and returns a context-aware reply.
      tags:
        - NLU
      operationId: sendMessage
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/BotRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/BotResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /chatbot/:
    get:
      summary: Find most recent recommendations by userId
      description: "Return the most recent restaurant recommendations based on the user's previous searches"
      operationId: "getUserById"
      produces:
        - application/json
      parameters:
        - name: "user_id"
          in: "query"
          description: "ID of current user"
          required: true
          type: "string"
          format: "string"
      responses:
        '200':
          description: A Chatbot response containing past searches
          schema:
            $ref: '#/definitions/DataMessage'
        '403':
          description: "Unauthorized/no data found"
          schema:
            $ref: '#/definitions/Error'
definitions:
  BotRequest:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  BotResponse:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  Message:
    type: object
    properties:
      type:
        type: string
      unstructured:
        $ref: '#/definitions/UnstructuredMessage'
  UnstructuredMessage:
    type: object
    properties:
      id:
        type: string
      text:
        type: string
      timestamp:
        type: string
        format: datetime
  DataMessage:
    type: object
    properties:
        data:
          $ref: '#/definitions/SearchResults'
  SearchResults:
    properties:
      search_results:
        type: array
        items:
          $ref: '#/definitions/SearchResult'
  SearchResult:
    type: object
    properties:
      name:
        type: string
      location:
        $ref: '#/definitions/DisplayAddress'
  DisplayAddress:
    type: array
    items:
      type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

